
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: uex_contacts_backend_development

test:
  <<: *default
  database: uex_contacts_backend_test

production:
  <<: *default
  database: uex_contacts_backend_production
  username: uex_contacts_backend
  password: <%= ENV["UEX_CONTACTS_BACKEND_DATABASE_PASSWORD"] %>
